export const DATABASE_ID_PROJECT = process.env.NOTION_DATABASE_ID_PROJECT;
export const DATABASE_ID_DESIGN = process.env.NOTION_DATABASE_ID_DESIGN;
export const DATABASE_ID_EXPRIENCE = process.env.NOTION_DATABASE_ID_EXPERIENCE;
export const TOKEN = process.env.NOTION_TOKEN;
